source 'https://rubygems.org'

gem 'discordrb'
gem 'rbnacl-libsodium'
gem 'aws-sdk'
gem 'image_size'
gem 'nokogiri'
gem 'httparty'
gem 'activerecord'
gem 'standalone_migrations'
gem 'mysql2'
gem 'cleverbot_io'
gem 'parallel'
gem 'm3u8'
gem 'rufus-scheduler'
